In [15]:
import pandas as pd

In [16]:
from nba_api.stats.endpoints import playercareerstats

# Nikola JokiÄ‡
career = playercareerstats.PlayerCareerStats(player_id='203999')

# pandas data frames (optional: pip install pandas)
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203999,2015-16,00,1610612743,DEN,21.0,80,55,1733.0,307,...,0.811,181,379,560,189,79,50,104,208,796
1,203999,2016-17,00,1610612743,DEN,22.0,73,59,2038.0,494,...,0.825,212,506,718,359,61,55,171,214,1221
2,203999,2017-18,00,1610612743,DEN,23.0,75,73,2443.0,504,...,0.850,195,608,803,458,90,61,210,212,1385
3,203999,2018-19,00,1610612743,DEN,24.0,80,80,2504.0,616,...,0.821,228,637,865,580,108,55,248,228,1604
4,203999,2019-20,00,1610612743,DEN,25.0,73,73,2335.0,565,...,0.817,166,545,711,512,85,44,226,222,1456
5,203999,2020-21,00,1610612743,DEN,26.0,72,72,2488.0,732,...,0.868,205,575,780,599,95,48,222,192,1898
6,203999,2021-22,00,1610612743,DEN,27.0,74,74,2476.0,764,...,0.810,206,813,1019,584,109,63,281,191,2004
7,203999,2022-23,00,1610612743,DEN,28.0,69,69,2323.0,646,...,0.822,167,650,817,678,87,47,247,174,1690
8,203999,2023-24,00,1610612743,DEN,29.0,66,66,2266.0,672,...,0.828,191,614,805,598,84,61,194,162,1708

In [17]:
career.get_dict()

{'resource': 'playercareerstats',
 'parameters': {'PerMode': 'Totals', 'PlayerID': 203999, 'LeagueID': None},
 'resultSets': [{'name': 'SeasonTotalsRegularSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '2015-16',
     '00',
     1610612743,
     'DEN',
     21.0,
     80,
     55,
     1733.0,
     307,
     600,
     0.512,
     28,
     84,
     0.333,
     154,
     190,
     0.811,
     181,
     379,
     560,
     189,
     79,
     50,
     104,
     208,
     796],
    [203999,
     '2016-17',
     '00',
     1610612743,
     'DEN',
     22.0,
     73,
     59,
     2038.0,
     494,
     854,
     0.578,
     45,
     139,
     0.324,
     188,
     228,
     0.825,
     212,
     506,
     718,
     359,
     61,
     55,
     171,
     214,
     1221],
    [203999,
     '2017-18',
     '00',
     1610612743,
     'DEN',
     23.0,
     75,
     73,
     2443.0,
     504,
     1010,
     0.499,
     111,
     280,
     0.396,
     266,
     313,
     0.85,
     195,
     608,
     803,
     458,
     90,
     61,
     210,
     212,
     1385],
    [203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     24.0,
     80,
     80,
     2504.0,
     616,
     1206,
     0.511,
     83,
     270,
     0.307,
     289,
     352,
     0.821,
     228,
     637,
     865,
     580,
     108,
     55,
     248,
     228,
     1604],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     25.0,
     73,
     73,
     2335.0,
     565,
     1071,
     0.528,
     80,
     255,
     0.314,
     246,
     301,
     0.817,
     166,
     545,
     711,
     512,
     85,
     44,
     226,
     222,
     1456],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     26.0,
     72,
     72,
     2488.0,
     732,
     1293,
     0.566,
     92,
     237,
     0.388,
     342,
     394,
     0.868,
     205,
     575,
     780,
     599,
     95,
     48,
     222,
     192,
     1898],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     27.0,
     74,
     74,
     2476.0,
     764,
     1311,
     0.583,
     97,
     288,
     0.337,
     379,
     468,
     0.81,
     206,
     813,
     1019,
     584,
     109,
     63,
     281,
     191,
     2004],
    [203999,
     '2022-23',
     '00',
     1610612743,
     'DEN',
     28.0,
     69,
     69,
     2323.0,
     646,
     1022,
     0.632,
     57,
     149,
     0.383,
     341,
     415,
     0.822,
     167,
     650,
     817,
     678,
     87,
     47,
     247,
     174,
     1690],
    [203999,
     '2023-24',
     '00',
     1610612743,
     'DEN',
     29.0,
     66,
     66,
     2266.0,
     672,
     1157,
     0.581,
     66,
     191,
     0.346,
     298,
     360,
     0.828,
     191,
     614,
     805,
     598,
     84,
     61,
     194,
     162,
     1708]]},
  {'name': 'CareerTotalsRegularSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '00',
     0,
     662,
     621,
     20604.0,
     5300,
     9524,
     0.556488,
     659,
     1893,
     0.348124,
     2503,
     3021,
     0.828533,
     1751,
     5327,
     7078,
     4557,
     798,
     484,
     1903,
     1803,
     13762]]},
  {'name': 'SeasonTotalsPostSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     24.0,
     14,
     14,
     556.0,
     132,
     261,
     0.506,
     22,
     56,
     0.393,
     66,
     78,
     0.846,
     54,
     128,
     182,
     118,
     16,
     13,
     36,
     54,
     352],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     25.0,
     19,
     19,
     694.0,
     178,
     343,
     0.519,
     42,
     98,
     0.429,
     66,
     79,
     0.835,
     37,
     150,
     187,
     109,
     20,
     15,
     62,
     68,
     464],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     26.0,
     10,
     10,
     345.0,
     116,
     228,
     0.509,
     20,
     53,
     0.377,
     46,
     55,
     0.836,
     37,
     79,
     116,
     50,
     6,
     9,
     24,
     23,
     298],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     27.0,
     5,
     5,
     171.0,
     61,
     106,
     0.575,
     5,
     18,
     0.278,
     28,
     33,
     0.848,
     17,
     49,
     66,
     29,
     8,
     5,
     24,
     20,
     155],
    [203999,
     '2022-23',
     '00',
     1610612743,
     'DEN',
     28.0,
     20,
     20,
     789.0,
     227,
     414,
     0.548,
     35,
     76,
     0.461,
     111,
     139,
     0.799,
     69,
     200,
     269,
     190,
     21,
     20,
     70,
     69,
     600]]},
  {'name': 'CareerTotalsPostSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '00',
     0,
     68,
     68,
     2556.0,
     714,
     1352,
     0.528106,
     124,
     301,
     0.41196,
     317,
     384,
     0.82552,
     214,
     606,
     820,
     496,
     71,
     62,
     216,
     234,
     1869]]},
  {'name': 'SeasonTotalsAllStarSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '2018-19',
     '00',
     1610616833,
     'GNS',
     24.0,
     1,
     0,
     13.0,
     3,
     4,
     0.75,
     0,
     0,
     0.0,
     0,
     0,
     0.0,
     3,
     6,
     9,
     0,
     0,
     0,
     1,
     1,
     6],
    [203999,
     '2019-20',
     '00',
     1610616834,
     'LBN',
     25.0,
     1,
     0,
     12.0,
     2,
     4,
     0.5,
     1,
     3,
     0.333,
     0,
     0,
     0.0,
     0,
     2,
     2,
     1,
     1,
     0,
     0,
     1,
     5],
    [203999,
     '2020-21',
     '00',
     1610616834,
     'LBN',
     26.0,
     1,
     1,
     19.0,
     3,
     4,
     0.75,
     0,
     0,
     0.0,
     0,
     0,
     0.0,
     0,
     7,
     7,
     5,
     0,
     1,
     2,
     1,
     6],
    [203999,
     '2021-22',
     '00',
     1610616834,
     'LBN',
     27.0,
     1,
     1,
     21.0,
     4,
     5,
     0.8,
     2,
     3,
     0.667,
     0,
     0,
     0.0,
     3,
     6,
     9,
     8,
     1,
     0,
     1,
     0,
     10],
    [203999,
     '2022-23',
     '00',
     1610616834,
     'LBN',
     28.0,
     1,
     1,
     20.0,
     2,
     4,
     0.5,
     0,
     1,
     0.0,
     0,
     0,
     0.0,
     3,
     2,
     5,
     6,
     2,
     0,
     2,
     0,
     4],
    [203999,
     '2023-24',
     '00',
     1610616834,
     'WST',
     29.0,
     1,
     1,
     23.0,
     6,
     8,
     0.75,
     1,
     1,
     1.0,
     0,
     0,
     0.0,
     3,
     1,
     4,
     9,
     2,
     0,
     1,
     1,
     13]]},
  {'name': 'CareerTotalsAllStarSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203999,
     '00',
     0,
     6,
     4,
     109.0,
     20,
     29,
     0.689655,
     4,
     8,
     0.5,
     0,
     0,
     0.0,
     12,
     24,
     36,
     29,
     6,
     1,
     7,
     4,
     44]]},
  {'name': 'SeasonTotalsCollegeSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'ORGANIZATION_ID',
    'SCHOOL_NAME',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'CareerTotalsCollegeSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'ORGANIZATION_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'SeasonTotalsShowcaseSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'CareerTotalsShowcaseSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'SeasonRankingsRegularSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'RANK_MIN',
    'RANK_FGM',
    'RANK_FGA',
    'RANK_FG_PCT',
    'RANK_FG3M',
    'RANK_FG3A',
    'RANK_FG3_PCT',
    'RANK_FTM',
    'RANK_FTA',
    'RANK_FT_PCT',
    'RANK_OREB',
    'RANK_DREB',
    'RANK_REB',
    'RANK_AST',
    'RANK_STL',
    'RANK_BLK',
    'RANK_TOV',
    'RANK_PTS',
    'RANK_EFF'],
   'rowSet': [[203999,
     '2015-16',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     152,
     112,
     135,
     18,
     223,
     227,
     None,
     90,
     104,
     58,
     24,
     45,
     38,
     82,
     61,
     68,
     115,
     120,
     50],
    [203999,
     '2016-17',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     108,
     34,
     68,
     6,
     192,
     188,
     None,
     61,
     65,
     46,
     12,
     17,
     13,
     31,
     106,
     51,
     32,
     41,
     17],
    [203999,
     '2017-18',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     40,
     29,
     36,
     29,
     88,
     99,
     35,
     25,
     30,
     26,
     10,
     8,
     7,
     12,
     38,
     47,
     16,
     26,
     8],
    [203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     34,
     19,
     25,
     31,
     128,
     107,
     128,
     28,
     34,
     52,
     10,
     9,
     8,
     6,
     19,
     53,
     9,
     22,
     4],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     11,
     11,
     21,
     19,
     127,
     102,
     142,
     29,
     30,
     56,
     14,
     8,
     8,
     6,
     25,
     63,
     8,
     18,
     3],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     3,
     1,
     8,
     14,
     117,
     132,
     75,
     12,
     14,
     26,
     8,
     7,
     5,
     3,
     11,
     55,
     5,
     3,
     1],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     18,
     2,
     8,
     8,
     121,
     110,
     120,
     9,
     8,
     63,
     13,
     1,
     1,
     6,
     10,
     34,
     5,
     5,
     1],
    [203999,
     '2022-23',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     47,
     13,
     47,
     8,
     208,
     220,
     None,
     23,
     22,
     58,
     25,
     3,
     3,
     2,
     28,
     62,
     5,
     17,
     1],
    [203999,
     '2023-24',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     13,
     4,
     13,
     12,
     169,
     158,
     None,
     17,
     18,
     49,
     8,
     2,
     3,
     2,
     11,
     30,
     11,
     7,
     1]]},
  {'name': 'SeasonRankingsPostSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'RANK_MIN',
    'RANK_FGM',
    'RANK_FGA',
    'RANK_FG_PCT',
    'RANK_FG3M',
    'RANK_FG3A',
    'RANK_FG3_PCT',
    'RANK_FTM',
    'RANK_FTA',
    'RANK_FT_PCT',
    'RANK_OREB',
    'RANK_DREB',
    'RANK_REB',
    'RANK_AST',
    'RANK_STL',
    'RANK_BLK',
    'RANK_TOV',
    'RANK_PTS',
    'RANK_EFF'],
   'rowSet': [[203999,
     '2018-19',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     13,
     7,
     9,
     14,
     20,
     28,
     29,
     8,
     10,
     27,
     1,
     6,
     4,
     4,
     18,
     14,
     12,
     10,
     4],
    [203999,
     '2019-20',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     6,
     4,
     4,
     12,
     10,
     16,
     19,
     10,
     10,
     31,
     4,
     2,
     4,
     4,
     11,
     8,
     2,
     5,
     3],
    [203999,
     '2020-21',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     37,
     13,
     13,
     18,
     36,
     38,
     44,
     14,
     15,
     30,
     8,
     16,
     12,
     20,
     58,
     25,
     19,
     14,
     13],
    [203999,
     '2021-22',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     85,
     32,
     44,
     7,
     97,
     90,
     79,
     32,
     34,
     21,
     26,
     38,
     35,
     44,
     51,
     53,
     27,
     38,
     37],
    [203999,
     '2022-23',
     '00',
     1610612743,
     'DEN',
     'NR',
     'NR',
     'NR',
     5,
     1,
     2,
     11,
     14,
     25,
     12,
     3,
     2,
     32,
     1,
     1,
     1,
     1,
     8,
     6,
     1,
     1,
     1]]}]}

In [18]:
from nba_api.stats.static import teams

# Find teams by full name.
teams.find_teams_by_full_name('cav')

[{'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970}]

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
from nba_api.stats.endpoints import teamgamelog

# Definisci l'ID della squadra (ad esempio, Los Angeles Lakers)
team_id_A = 1610612747

team_id_B = 1610612739

# Ottieni i dati delle partite passate della squadra specificata
game_log_A = teamgamelog.TeamGameLog(team_id_A)

# Ottieni i dati dei DataFrame
game_log_data_A = game_log_A.get_data_frames()

# Stampa i dati delle partite passate
game_log_data_A[0]

game_log_B = teamgamelog.TeamGameLog(team_id_B)
game_log_data_B = game_log_B.get_data_frames()
game_log_data_B[0]

,Team_ID,Game_ID,GAME_DATE,MATCHUP,WL,W,L,W_PCT,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1610612739,0022300983,"MAR 18, 2024",CLE @ IND,W,43,25,0.632,240,38,...,0.714,9,30,39,27,8,4,14,18,108
1,1610612739,0022300967,"MAR 16, 2024",CLE @ HOU,L,42,25,0.627,240,37,...,0.850,7,38,45,22,6,7,15,12,103
2,1610612739,0022300951,"MAR 13, 2024",CLE @ NOP,W,42,24,0.636,240,47,...,0.667,8,38,46,38,4,4,9,18,116
3,1610612739,0022300934,"MAR 11, 2024",CLE vs. PHX,L,41,24,0.631,240,40,...,0.842,10,27,37,30,9,0,12,18,111
4,1610612739,0022300930,"MAR 10, 2024",CLE vs. BKN,L,41,23,0.641,240,37,...,0.650,5,26,31,25,8,4,12,17,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,1610612739,0022300120,"NOV 01, 2023",CLE @ NYK,W,2,3,0.400,240,32,...,0.950,6,40,46,22,7,5,18,27,95
64,1610612739,0022300112,"OCT 31, 2023",CLE vs. NYK,L,1,3,0.250,240,36,...,0.750,14,32,46,19,6,6,15,19,91
65,1610612739,0022300091,"OCT 28, 2023",CLE vs. IND,L,1,2,0.333,240,43,...,0.625,18,33,51,29,2,6,6,16,113
66,1610612739,0022300081,"OCT 27, 2023",CLE vs. OKC,L,1,1,0.500,240,38,...,0.739,8,40,48,20,10,8,13,16,105
67,1610612739,0022300067,"OCT 25, 2023",CLE @ BKN,W,1,0,1.000,240,44,...,0.900,9,29,38,25,10,6,10,23,114

In [21]:
dati_partite = game_log_data_A[0].join(game_log_data_B[0], lsuffix='_A', rsuffix='_B')
dati_partite

,Team_ID_A,Game_ID_A,GAME_DATE_A,MATCHUP_A,WL_A,W_A,L_A,W_PCT_A,MIN_A,FGM_A,...,FT_PCT_B,OREB_B,DREB_B,REB_B,AST_B,STL_B,BLK_B,TOV_B,PF_B,PTS_B
0,1610612747,0022300990,"MAR 18, 2024",LAL vs. ATL,W,37,32,0.536,240,52,...,0.714,9.0,30.0,39.0,27.0,8.0,4.0,14.0,18.0,108.0
1,1610612747,0022300973,"MAR 16, 2024",LAL vs. GSW,L,36,32,0.529,240,47,...,0.850,7.0,38.0,45.0,22.0,6.0,7.0,15.0,12.0,103.0
2,1610612747,0022300954,"MAR 13, 2024",LAL @ SAC,L,36,31,0.537,240,38,...,0.667,8.0,38.0,46.0,38.0,4.0,4.0,9.0,18.0,116.0
3,1610612747,0022300932,"MAR 10, 2024",LAL vs. MIN,W,36,30,0.545,240,44,...,0.842,10.0,27.0,37.0,30.0,9.0,0.0,12.0,18.0,111.0
4,1610612747,0022300915,"MAR 08, 2024",LAL vs. MIL,W,35,30,0.538,240,47,...,0.650,5.0,26.0,31.0,25.0,8.0,4.0,12.0,17.0,101.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,1610612747,0022300127,"NOV 01, 2023",LAL vs. LAC,W,3,2,0.600,265,46,...,0.750,14.0,32.0,46.0,19.0,6.0,6.0,15.0,19.0,91.0
65,1610612747,0022300111,"OCT 30, 2023",LAL vs. ORL,W,2,2,0.500,240,42,...,0.625,18.0,33.0,51.0,29.0,2.0,6.0,6.0,16.0,113.0
66,1610612747,0022300100,"OCT 29, 2023",LAL @ SAC,L,1,2,0.333,265,43,...,0.739,8.0,40.0,48.0,20.0,10.0,8.0,13.0,16.0,105.0
67,1610612747,0022300076,"OCT 26, 2023",LAL vs. PHX,W,1,1,0.500,240,36,...,0.900,9.0,29.0,38.0,25.0,10.0,6.0,10.0,23.0,114.0
68,1610612747,0022300061,"OCT 24, 2023",LAL @ DEN,L,0,1,0.000,240,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Match precedenti tra squadra1 e squadra2

In [22]:
# from nba_api.stats.endpoints import teamgamelog
# from nba_api.stats.static import teams

# # Definisci gli ID delle squadre (ad esempio, Los Angeles Lakers e Boston Celtics)
# team_id1 = 1610612747  # Los Angeles Lakers
# team_id2 = 1610612738  # Boston Celtics
 
# # Ottieni i dati delle partite giocate da ciascuna squadra
# team1_log = teamgamelog.TeamGameLog(team_id1).get_data_frames()[0]
# team2_log = teamgamelog.TeamGameLog(team_id2).get_data_frames()[0]
 
 
# abbreviation = teams.find_team_name_by_id(team_id2)["abbreviation"]

# # Trova le partite in cui le due squadre si sono affrontate
# head_to_head_games = team1_log[team1_log['MATCHUP'].str.contains(abbreviation)]  # Assumendo che la convenzione MATCHUP sia "<team> vs. <opponent>"
 
# # Stampa i dati dei precedenti tra le due squadre
# head_to_head_games

In [23]:
from nba_api.stats.endpoints import leaguegamelog
from nba_api.stats.endpoints import teamgamelog
from nba_api.stats.static import teams

# Definisci gli ID delle squadre (ad esempio, Los Angeles Lakers e Boston Celtics)
team_id1 = 1610612747  # Los Angeles Lakers
team_id2 = 1610612738  # Boston Celtics

def match_A_B():
    final_df = pd.DataFrame()
    for i in range(0,4):
        season = f"202{i}-2{i+1}"
        abbreviation_A = teams.find_team_name_by_id(team_id1)["abbreviation"]
        abbreviation_B = teams.find_team_name_by_id(team_id2)["abbreviation"]
        
        # Ottieni i dettagli delle partite giocate nella stagione specificata
        game_log = leaguegamelog.LeagueGameLog(season=season)
        
        # Ottieni i dati dei DataFrame
        game_log_data = game_log.get_data_frames()
        
        # Stampa i dettagli delle partite giocate nella stagione specificata
        game_log_data = game_log_data[0][game_log_data[0]['TEAM_ID'] == team_id1]
        
        game_log_data_A_B = game_log_data[game_log_data['MATCHUP'].str.contains(abbreviation_B)]
        
        final_df = pd.concat([final_df, game_log_data_A_B], axis = 0)
    return final_df

final_df = match_A_B()

final_df

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
554,22020,1610612747,LAL,Los Angeles Lakers,0022000302,2021-01-30,LAL @ BOS,W,240,37,...,32,45,20,8,4,14,15,96,1,1
1645,22020,1610612747,LAL,Los Angeles Lakers,0022000842,2021-04-15,LAL vs. BOS,L,240,44,...,25,36,28,12,2,8,16,113,-8,1
465,22021,1610612747,LAL,Los Angeles Lakers,0022100232,2021-11-19,LAL @ BOS,L,240,39,...,26,33,20,5,6,12,29,108,-22,1
728,22021,1610612747,LAL,Los Angeles Lakers,0022100365,2021-12-07,LAL vs. BOS,W,240,48,...,38,51,25,7,4,16,21,117,15,1
818,22022,1610612747,LAL,Los Angeles Lakers,0022200413,2022-12-13,LAL vs. BOS,L,265,44,...,42,49,23,7,9,12,17,118,-4,1
1480,22022,1610612747,LAL,Los Angeles Lakers,0022200749,2023-01-28,LAL @ BOS,L,265,47,...,36,47,30,4,0,12,23,121,-4,1
865,22023,1610612747,LAL,Los Angeles Lakers,0022300403,2023-12-25,LAL vs. BOS,L,240,43,...,30,43,24,4,1,12,19,115,-11,1
1426,22023,1610612747,LAL,Los Angeles Lakers,0022300684,2024-02-01,LAL @ BOS,W,240,38,...,37,52,30,11,2,7,8,114,9,1

In [24]:
from nba_api.stats.endpoints import leaguegamelog
 
# Specifica la stagione di interesse (ad esempio, la stagione 2020-2021)
season = '2010-11'
 
# Ottieni i dettagli delle partite giocate nella stagione specificata
game_log = leaguegamelog.LeagueGameLog(season=season)
 
# Ottieni i dati dei DataFrame
game_log_data = game_log.get_data_frames()
 
# Stampa i dettagli delle partite giocate nella stagione specificata
game_log_data[0]

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22010,1610612745,HOU,Houston Rockets,0021000003,2010-10-26,HOU @ LAL,L,240,38,...,37,53,25,6,7,21,25,110,-2,0
1,22010,1610612747,LAL,Los Angeles Lakers,0021000003,2010-10-26,LAL vs. HOU,W,240,40,...,30,44,21,11,4,12,24,112,2,0
2,22010,1610612757,POR,Portland Trail Blazers,0021000002,2010-10-26,POR vs. PHX,W,240,43,...,30,48,31,11,2,15,22,106,14,0
3,22010,1610612756,PHX,Phoenix Suns,0021000002,2010-10-26,PHX @ POR,L,240,36,...,23,30,15,3,4,19,19,92,-14,0
4,22010,1610612748,MIA,Miami Heat,0021000001,2010-10-26,MIA @ BOS,L,240,27,...,28,39,15,10,6,17,21,80,-8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,22010,1610612761,TOR,Toronto Raptors,0021001221,2011-04-13,TOR vs. MIA,L,240,28,...,23,33,16,8,8,17,15,79,-18,0
2456,22010,1610612751,NJN,New Jersey Nets,0021001222,2011-04-13,NJN @ CHI,L,240,36,...,27,35,21,6,6,13,19,92,-5,0
2457,22010,1610612741,CHI,Chicago Bulls,0021001222,2011-04-13,CHI vs. NJN,W,240,34,...,30,45,23,3,9,13,20,97,5,0
2458,22010,1610612748,MIA,Miami Heat,0021001221,2011-04-13,MIA @ TOR,W,240,37,...,27,40,20,6,1,15,18,97,18,0
2459,22010,1610612740,NOH,New Orleans Hornets,0021001223,2011-04-13,NOH @ DAL,L,240,34,...,30,35,23,7,1,14,28,89,-32,0

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X = dati_partite[['Feature1', 'Feature2', ...]]  # Seleziona le caratteristiche rilevanti
y = dati_partite['Risultato']  # Etichetta di output (1 per vittoria della squadra A, 0 per vittoria della squadra B)

# Dividi i dati in set di addestramento e set di test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inizializza il modello di regressione logistica
model = LogisticRegression()

# Addestra il modello
model.fit(X_train, y_train)

# Effettua previsioni sul set di test
predictions = model.predict(X_test)

# Valuta le prestazioni del modello
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

KeyError: "None of [Index(['Feature1', 'Feature2', Ellipsis], dtype='object')] are in the [columns]"