In [1]:
import pandas as pd

In [2]:
from nba_api.stats.endpoints import playercareerstats

# Nikola JokiÄ‡
career = playercareerstats.PlayerCareerStats(player_id='203999')

# pandas data frames (optional: pip install pandas)
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203999,2015-16,00,1610612743,DEN,21.0,80,55,1733.0,307,...,0.811,181,379,560,189,79,50,104,208,796
1,203999,2016-17,00,1610612743,DEN,22.0,73,59,2038.0,494,...,0.825,212,506,718,359,61,55,171,214,1221
2,203999,2017-18,00,1610612743,DEN,23.0,75,73,2443.0,504,...,0.850,195,608,803,458,90,61,210,212,1385
3,203999,2018-19,00,1610612743,DEN,24.0,80,80,2504.0,616,...,0.821,228,637,865,580,108,55,248,228,1604
4,203999,2019-20,00,1610612743,DEN,25.0,73,73,2335.0,565,...,0.817,166,545,711,512,85,44,226,222,1456
5,203999,2020-21,00,1610612743,DEN,26.0,72,72,2488.0,732,...,0.868,205,575,780,599,95,48,222,192,1898
6,203999,2021-22,00,1610612743,DEN,27.0,74,74,2476.0,764,...,0.810,206,813,1019,584,109,63,281,191,2004
7,203999,2022-23,00,1610612743,DEN,28.0,69,69,2323.0,646,...,0.822,167,650,817,678,87,47,247,174,1690
8,203999,2023-24,00,1610612743,DEN,29.0,66,66,2266.0,672,...,0.828,191,614,805,598,84,61,194,162,1708

In [12]:
career.get_data_frames()[0].columns

Index(['PLAYER_ID', 'SEASON_ID', 'LEAGUE_ID', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [13]:
from nba_api.stats.endpoints import playergamelog

# Definisci l'ID del giocatore di interesse
player_id = '201935'  # Ad esempio, questo Ã¨ l'ID di James Harden

# Ottieni i dati delle partite del giocatore
gamelog = playergamelog.PlayerGameLog(player_id=player_id)

# Ottieni i dati dei DataFrame
gamelog_data = gamelog.get_data_frames()

# Stampa le statistiche delle partite del giocatore
gamelog_data[0]

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22023,201935,0022300982,"MAR 17, 2024",LAC vs. ATL,L,36,3,10,0.300,...,6,6,9,1,1,3,2,9,-15,1
1,22023,201935,0022300944,"MAR 12, 2024",LAC vs. MIN,L,34,4,10,0.400,...,2,2,7,2,0,4,1,12,-15,1
2,22023,201935,0022300924,"MAR 10, 2024",LAC vs. MIL,L,36,5,16,0.313,...,2,5,11,0,0,5,4,13,-13,1
3,22023,201935,0022300917,"MAR 09, 2024",LAC vs. CHI,W,34,4,10,0.400,...,11,11,10,1,0,1,2,14,4,1
4,22023,201935,0022300897,"MAR 06, 2024",LAC @ HOU,W,39,6,13,0.462,...,5,5,7,1,1,2,2,21,8,1
5,22023,201935,0022300880,"MAR 04, 2024",LAC @ MIL,L,37,9,16,0.563,...,4,4,8,0,1,3,2,29,-4,1
6,22023,201935,0022300873,"MAR 03, 2024",LAC @ MIN,W,34,0,10,0.000,...,5,5,10,1,2,1,1,4,-10,1
7,22023,201935,0022300865,"MAR 01, 2024",LAC vs. WAS,W,25,9,13,0.692,...,3,4,8,0,3,3,1,28,19,1
8,22023,201935,0022300848,"FEB 28, 2024",LAC vs. LAL,L,40,8,16,0.500,...,2,3,9,1,0,4,1,23,-12,1
9,22023,201935,0022300827,"FEB 25, 2024",LAC vs. SAC,L,35,4,13,0.308,...,5,5,8,0,0,3,3,20,-25,1
10,22023,201935,0022300807,"FEB 23, 2024",LAC @ MEM,W,39,1,8,0.125,...,7,8,8,0,1,4,0,9,3,1
11,22023,201935,0022300799,"FEB 22, 2024",LAC @ OKC,L,29,5,9,0.556,...,4,6,2,1,0,3,2,17,-7,1
12,22023,201935,0022300789,"FEB 14, 2024",LAC @ GSW,W,40,7,12,0.583,...,6,8,7,0,1,1,0,26,13,2
13,22023,201935,0022300770,"FEB 12, 2024",LAC vs. MIN,L,32,5,13,0.385,...,2,2,6,1,1,0,0,17,-9,1
14,22023,201935,0022300749,"FEB 10, 2024",LAC vs. DET,W,36,4,11,0.364,...,6,6,8,1,1,5,1,14,8,1
15,22023,201935,0022300731,"FEB 07, 2024",LAC vs. NOP,L,38,6,11,0.545,...,7,8,5,1,1,4,2,19,-1,1
16,22023,201935,0022300716,"FEB 05, 2024",LAC @ ATL,W,39,7,14,0.500,...,6,8,10,2,1,2,3,30,11,1
17,22023,201935,0022300708,"FEB 04, 2024",LAC @ MIA,W,42,7,13,0.538,...,8,8,11,1,1,4,1,21,10,1
18,22023,201935,0022300688,"FEB 02, 2024",LAC @ DET,W,34,1,10,0.100,...,2,3,6,1,0,1,1,4,8,1
19,22023,201935,0022300676,"JAN 31, 2024",LAC @ WAS,W,33,7,15,0.467,...,8,9,5,2,4,2,2,25,20,1
20,22023,201935,0022300658,"JAN 29, 2024",LAC @ CLE,L,39,3,8,0.375,...,7,7,10,1,1,3,2,11,-2,1
21,22023,201935,0022300646,"JAN 27, 2024",LAC @ BOS,W,27,2,11,0.182,...,7,8,7,0,0,1,2,9,36,1
22,22023,201935,0022300637,"JAN 26, 2024",LAC @ TOR,W,35,8,14,0.571,...,10,10,13,1,1,1,3,22,27,1
23,22023,201935,0022300618,"JAN 23, 2024",LAC vs. LAL,W,39,8,17,0.471,...,1,2,10,1,1,1,3,23,10,1
24,22023,201935,0022300600,"JAN 21, 2024",LAC vs. BKN,W,38,6,11,0.545,...,5,5,10,2,1,4,2,24,9,1
25,22023,201935,0022300568,"JAN 16, 2024",LAC vs. OKC,W,41,5,14,0.357,...,5,5,8,0,1,1,2,16,8,1
26,22023,201935,0022300553,"JAN 14, 2024",LAC @ MIN,L,36,4,14,0.286,...,1,1,8,2,2,4,3,14,-3,1
27,22023,201935,0022300537,"JAN 12, 2024",LAC @ MEM,W,28,3,7,0.429,...,1,1,9,1,0,3,0,11,20,1
28,22023,201935,0022300526,"JAN 10, 2024",LAC vs. TOR,W,34,5,13,0.385,...,5,5,11,1,0,3,4,14,8,1
29,22023,201935,0022300511,"JAN 08, 2024",LAC vs. PHX,W,30,6,8,0.750,...,7,7,10,0,0,3,1,19,25,1
30,22023,201935,0022300505,"JAN 07, 2024",LAC @ LAL,L,39,4,13,0.308,...,2,4,9,1,0,5,3,15,-1,1
31,22023,201935,0022300486,"JAN 05, 2024",LAC @ NOP,W,29,2,7,0.286,...,3,3,13,0,0,1,2,8,18,1
32,22023,201935,0022300473,"JAN 03, 2024",LAC @ PHX,W,36,7,13,0.538,...,5,5,11,0,1,4,2,22,1,1
33,22023,201935,0022300458,"JAN 01, 2024",LAC vs. MIA,W,31,5,8,0.625,...,4,4,10,1,2,2,1,15,26,1
34,22023,201935,0022300438,"DEC 29, 2023",LAC vs. MEM,W,44,4,13,0.308,...,4,4,13,0,3,5,1,16,16,1
35,22023,201935,0022300414,"DEC 26, 2023",LAC vs. CHA,W,40,8,16,0.500,...,6,6,8,2,1,4,2,29,20,1
36,22023,201935,0022300389,"DEC 23, 2023",LAC vs. BOS,L,29,6,13,0.462,...,4,4,9,1,0,4,4,14,-34,1
37,22023,201935,0022300379,"DEC 21, 2023",LAC @ OKC,L,34,7,18,0.389,...,7,9,6,3,1,3,1,23,-17,1
38,22023,201935,0022300372,"DEC 20, 2023",LAC @ DAL,W,39,4,12,0.333,...,5,5,11,0,2,4,3,17,10,1
39,22023,201935,0022300350,"DEC 18, 2023",LAC @ IND,W,28,12,16,0.750,...,3,3,9,1,1,1,2,35,32,1
40,22023,201935,0022300343,"DEC 16, 2023",LAC vs. NYK,W,28,2,6,0.333,...,4,4,12,1,2,1,3,10,22,1
41,22023,201935,0022300325,"DEC 14, 2023",LAC vs. GSW,W,42,6,12,0.500,...,5,7,15,1,4,4,3,28,12,1
42,22023,201935,0022300309,"DEC 12, 2023",LAC vs. SAC,W,28,4,9,0.444,...,6,6,7,2,0,2,3,15,26,1
43,22023,201935,0022300304,"DEC 11, 2023",LAC vs. POR,W,37,7,14,0.500,...,7,7,7,1,2,3,2,20,3,1
44,22023,201935,0022301225,"DEC 08, 2023",LAC @ UTA,W,34,2,8,0.250,...,7,7,8,0,1,2,2,12,18,1
45,22023,201935,0022301215,"DEC 06, 2023",LAC vs. DEN,W,32,6,10,0.600,...,1,1,11,3,1,4,0,20,6,1
46,22023,201935,0022300280,"DEC 02, 2023",LAC vs. GSW,W,35,7,14,0.500,...,5,5,9,1,0,1,4,21,0,1
47,22023,201935,0022300273,"NOV 30, 2023",LAC @ GSW,L,37,6,13,0.462,...,3,3,7,1,0,1,3,18,-1,1
48,22023,201935,0022300264,"NOV 29, 2023",LAC @ SAC,W,39,8,14,0.571,...,2,3,6,5,0,2,4,26,19,1
49,22023,201935,0022300257,"NOV 27, 2023",LAC vs. DEN,L,36,3,7,0.429,...,2,2,4,1,0,3,3,11,6,1
50,22023,201935,0022300244,"NOV 25, 2023",LAC vs. DAL,W,28,2,8,0.250,...,4,4,7,1,2,2,1,8,14,1
51,22023,201935,0022300052,"NOV 24, 2023",LAC vs. NOP,L,37,2,8,0.250,...,5,5,10,4,1,3,3,8,-6,1
52,22023,201935,0022300235,"NOV 22, 2023",LAC @ SAS,W,36,3,7,0.429,...,6,6,9,1,1,4,3,16,-2,1
53,22023,201935,0022300223,"NOV 20, 2023",LAC @ SAS,W,28,4,12,0.333,...,2,3,10,2,0,0,2,13,17,1
54,22023,201935,0022300037,"NOV 17, 2023",LAC vs. HOU,W,34,8,11,0.727,...,8,9,7,0,1,3,1,24,21,1
55,22023,201935,0022300024,"NOV 14, 2023",LAC @ DEN,L,35,7,15,0.467,...,2,2,4,0,0,1,3,21,-3,1
56,22023,201935,0022300179,"NOV 12, 2023",LAC vs. MEM,L,29,4,12,0.333,...,2,4,3,1,1,1,0,11,-28,1
57,22023,201935,0022300014,"NOV 10, 2023",LAC @ DAL,L,29,3,6,0.500,...,5,5,3,2,0,2,0,14,-6,1
58,22023,201935,0022300160,"NOV 08, 2023",LAC @ BKN,L,36,4,9,0.444,...,8,8,5,2,0,5,0,12,-15,1
59,22023,201935,0022300151,"NOV 06, 2023",LAC @ NYK,L,31,6,9,0.667,...,3,3,6,1,0,2,2,17,-18,1

In [15]:
gamelog_data[0].columns

Index(['SEASON_ID', 'Player_ID', 'Game_ID', 'GAME_DATE', 'MATCHUP', 'WL',
       'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE'],
      dtype='object')

In [112]:
career.get_dict().to_pandas()

AttributeError: 'dict' object has no attribute 'to_pandas'

In [4]:
from nba_api.stats.static import teams

# Find teams by full name.
teams.find_teams_by_full_name('cav')

[{'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970}]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
from nba_api.stats.endpoints import teamgamelog

# Definisci l'ID della squadra (ad esempio, Los Angeles Lakers)
team_id_A = 1610612747

team_id_B = 1610612739

# Ottieni i dati delle partite passate della squadra specificata
game_log_A = teamgamelog.TeamGameLog(team_id_A)

# Ottieni i dati dei DataFrame
game_log_data_A = game_log_A.get_data_frames()

# Stampa i dati delle partite passate
game_log_data_A[0]

game_log_B = teamgamelog.TeamGameLog(team_id_B)
game_log_data_B = game_log_B.get_data_frames()
game_log_data_B[0]

,Team_ID,Game_ID,GAME_DATE,MATCHUP,WL,W,L,W_PCT,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1610612739,0022300983,"MAR 18, 2024",CLE @ IND,W,43,25,0.632,240,38,...,0.714,9,30,39,27,8,4,14,18,108
1,1610612739,0022300967,"MAR 16, 2024",CLE @ HOU,L,42,25,0.627,240,37,...,0.850,7,38,45,22,6,7,15,12,103
2,1610612739,0022300951,"MAR 13, 2024",CLE @ NOP,W,42,24,0.636,240,47,...,0.667,8,38,46,38,4,4,9,18,116
3,1610612739,0022300934,"MAR 11, 2024",CLE vs. PHX,L,41,24,0.631,240,40,...,0.842,10,27,37,30,9,0,12,18,111
4,1610612739,0022300930,"MAR 10, 2024",CLE vs. BKN,L,41,23,0.641,240,37,...,0.650,5,26,31,25,8,4,12,17,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,1610612739,0022300120,"NOV 01, 2023",CLE @ NYK,W,2,3,0.400,240,32,...,0.950,6,40,46,22,7,5,18,27,95
64,1610612739,0022300112,"OCT 31, 2023",CLE vs. NYK,L,1,3,0.250,240,36,...,0.750,14,32,46,19,6,6,15,19,91
65,1610612739,0022300091,"OCT 28, 2023",CLE vs. IND,L,1,2,0.333,240,43,...,0.625,18,33,51,29,2,6,6,16,113
66,1610612739,0022300081,"OCT 27, 2023",CLE vs. OKC,L,1,1,0.500,240,38,...,0.739,8,40,48,20,10,8,13,16,105
67,1610612739,0022300067,"OCT 25, 2023",CLE @ BKN,W,1,0,1.000,240,44,...,0.900,9,29,38,25,10,6,10,23,114

In [7]:
dati_partite = game_log_data_A[0].join(game_log_data_B[0], lsuffix='_A', rsuffix='_B')
dati_partite

,Team_ID_A,Game_ID_A,GAME_DATE_A,MATCHUP_A,WL_A,W_A,L_A,W_PCT_A,MIN_A,FGM_A,...,FT_PCT_B,OREB_B,DREB_B,REB_B,AST_B,STL_B,BLK_B,TOV_B,PF_B,PTS_B
0,1610612747,0022300990,"MAR 18, 2024",LAL vs. ATL,W,37,32,0.536,240,52,...,0.714,9.0,30.0,39.0,27.0,8.0,4.0,14.0,18.0,108.0
1,1610612747,0022300973,"MAR 16, 2024",LAL vs. GSW,L,36,32,0.529,240,47,...,0.850,7.0,38.0,45.0,22.0,6.0,7.0,15.0,12.0,103.0
2,1610612747,0022300954,"MAR 13, 2024",LAL @ SAC,L,36,31,0.537,240,38,...,0.667,8.0,38.0,46.0,38.0,4.0,4.0,9.0,18.0,116.0
3,1610612747,0022300932,"MAR 10, 2024",LAL vs. MIN,W,36,30,0.545,240,44,...,0.842,10.0,27.0,37.0,30.0,9.0,0.0,12.0,18.0,111.0
4,1610612747,0022300915,"MAR 08, 2024",LAL vs. MIL,W,35,30,0.538,240,47,...,0.650,5.0,26.0,31.0,25.0,8.0,4.0,12.0,17.0,101.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,1610612747,0022300127,"NOV 01, 2023",LAL vs. LAC,W,3,2,0.600,265,46,...,0.750,14.0,32.0,46.0,19.0,6.0,6.0,15.0,19.0,91.0
65,1610612747,0022300111,"OCT 30, 2023",LAL vs. ORL,W,2,2,0.500,240,42,...,0.625,18.0,33.0,51.0,29.0,2.0,6.0,6.0,16.0,113.0
66,1610612747,0022300100,"OCT 29, 2023",LAL @ SAC,L,1,2,0.333,265,43,...,0.739,8.0,40.0,48.0,20.0,10.0,8.0,13.0,16.0,105.0
67,1610612747,0022300076,"OCT 26, 2023",LAL vs. PHX,W,1,1,0.500,240,36,...,0.900,9.0,29.0,38.0,25.0,10.0,6.0,10.0,23.0,114.0
68,1610612747,0022300061,"OCT 24, 2023",LAL @ DEN,L,0,1,0.000,240,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Match precedenti tra squadra1 e squadra2

In [8]:
# from nba_api.stats.endpoints import teamgamelog
# from nba_api.stats.static import teams

# # Definisci gli ID delle squadre (ad esempio, Los Angeles Lakers e Boston Celtics)
# team_id1 = 1610612747  # Los Angeles Lakers
# team_id2 = 1610612738  # Boston Celtics
 
# # Ottieni i dati delle partite giocate da ciascuna squadra
# team1_log = teamgamelog.TeamGameLog(team_id1).get_data_frames()[0]
# team2_log = teamgamelog.TeamGameLog(team_id2).get_data_frames()[0]
 
 
# abbreviation = teams.find_team_name_by_id(team_id2)["abbreviation"]

# # Trova le partite in cui le due squadre si sono affrontate
# head_to_head_games = team1_log[team1_log['MATCHUP'].str.contains(abbreviation)]  # Assumendo che la convenzione MATCHUP sia "<team> vs. <opponent>"
 
# # Stampa i dati dei precedenti tra le due squadre
# head_to_head_games

In [9]:
from nba_api.stats.endpoints import leaguegamelog
from nba_api.stats.endpoints import teamgamelog
from nba_api.stats.static import teams

# Definisci gli ID delle squadre (ad esempio, Los Angeles Lakers e Boston Celtics)
team_id1 = 1610612747  # Los Angeles Lakers
team_id2 = 1610612738  # Boston Celtics

def match_A_B():
    final_df = pd.DataFrame()
    for i in range(0,4):
        season = f"202{i}-2{i+1}"
        abbreviation_A = teams.find_team_name_by_id(team_id1)["abbreviation"]
        abbreviation_B = teams.find_team_name_by_id(team_id2)["abbreviation"]
        
        # Ottieni i dettagli delle partite giocate nella stagione specificata
        game_log = leaguegamelog.LeagueGameLog(season=season)
        
        # Ottieni i dati dei DataFrame
        game_log_data = game_log.get_data_frames()
        
        # Stampa i dettagli delle partite giocate nella stagione specificata
        game_log_data = game_log_data[0][game_log_data[0]['TEAM_ID'] == team_id1]
        
        game_log_data_A_B = game_log_data[game_log_data['MATCHUP'].str.contains(abbreviation_B)]
        
        final_df = pd.concat([final_df, game_log_data_A_B], axis = 0)
    return final_df

final_df = match_A_B()

final_df

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
553,22020,1610612747,LAL,Los Angeles Lakers,0022000302,2021-01-30,LAL @ BOS,W,240,37,...,32,45,20,8,4,14,15,96,1,1
1642,22020,1610612747,LAL,Los Angeles Lakers,0022000842,2021-04-15,LAL vs. BOS,L,240,44,...,25,36,28,12,2,8,16,113,-8,1
472,22021,1610612747,LAL,Los Angeles Lakers,0022100232,2021-11-19,LAL @ BOS,L,240,39,...,26,33,20,5,6,12,29,108,-22,1
729,22021,1610612747,LAL,Los Angeles Lakers,0022100365,2021-12-07,LAL vs. BOS,W,240,48,...,38,51,25,7,4,16,21,117,15,1
822,22022,1610612747,LAL,Los Angeles Lakers,0022200413,2022-12-13,LAL vs. BOS,L,265,44,...,42,49,23,7,9,12,17,118,-4,1
1497,22022,1610612747,LAL,Los Angeles Lakers,0022200749,2023-01-28,LAL @ BOS,L,265,47,...,36,47,30,4,0,12,23,121,-4,1
865,22023,1610612747,LAL,Los Angeles Lakers,0022300403,2023-12-25,LAL vs. BOS,L,240,43,...,30,43,24,4,1,12,19,115,-11,1
1426,22023,1610612747,LAL,Los Angeles Lakers,0022300684,2024-02-01,LAL @ BOS,W,240,38,...,37,52,30,11,2,7,8,114,9,1

In [10]:
from nba_api.stats.endpoints import leaguegamelog
 
# Specifica la stagione di interesse (ad esempio, la stagione 2020-2021)
season = '2010-11'
 
# Ottieni i dettagli delle partite giocate nella stagione specificata
game_log = leaguegamelog.LeagueGameLog(season=season)
 
# Ottieni i dati dei DataFrame
game_log_data = game_log.get_data_frames()
 
# Stampa i dettagli delle partite giocate nella stagione specificata
game_log_data[0]

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22010,1610612748,MIA,Miami Heat,0021000001,2010-10-26,MIA @ BOS,L,240,27,...,28,39,15,10,6,17,21,80,-8,0
1,22010,1610612756,PHX,Phoenix Suns,0021000002,2010-10-26,PHX @ POR,L,240,36,...,23,30,15,3,4,19,19,92,-14,0
2,22010,1610612757,POR,Portland Trail Blazers,0021000002,2010-10-26,POR vs. PHX,W,240,43,...,30,48,31,11,2,15,22,106,14,0
3,22010,1610612747,LAL,Los Angeles Lakers,0021000003,2010-10-26,LAL vs. HOU,W,240,40,...,30,44,21,11,4,12,24,112,2,0
4,22010,1610612745,HOU,Houston Rockets,0021000003,2010-10-26,HOU @ LAL,L,240,38,...,37,53,25,6,7,21,25,110,-2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,22010,1610612749,MIL,Milwaukee Bucks,0021001225,2011-04-13,MIL @ OKC,W,265,40,...,26,34,22,15,6,13,15,110,4,0
2456,22010,1610612748,MIA,Miami Heat,0021001221,2011-04-13,MIA @ TOR,W,240,37,...,27,40,20,6,1,15,18,97,18,0
2457,22010,1610612761,TOR,Toronto Raptors,0021001221,2011-04-13,TOR vs. MIA,L,240,28,...,23,33,16,8,8,17,15,79,-18,0
2458,22010,1610612752,NYK,New York Knicks,0021001216,2011-04-13,NYK @ BOS,L,240,39,...,25,37,22,8,5,16,16,102,-10,0
2459,22010,1610612751,NJN,New Jersey Nets,0021001222,2011-04-13,NJN @ CHI,L,240,36,...,27,35,21,6,6,13,19,92,-5,0

In [11]:
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score

# X = dati_partite[['Feature1', 'Feature2', ...]]  # Seleziona le caratteristiche rilevanti
# y = dati_partite['Risultato']  # Etichetta di output (1 per vittoria della squadra A, 0 per vittoria della squadra B)

# # Dividi i dati in set di addestramento e set di test

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Inizializza il modello di regressione logistica
# model = LogisticRegression()

# # Addestra il modello
# model.fit(X_train, y_train)

# # Effettua previsioni sul set di test
# predictions = model.predict(X_test)

# # Valuta le prestazioni del modello
# accuracy = accuracy_score(y_test, predictions)
# print("Accuracy:", accuracy)

KeyError: "None of [Index(['Feature1', 'Feature2', Ellipsis], dtype='object')] are in the [columns]"

# Per ogni partita la squadra titolare

In [ ]:
from nba_api.stats.endpoints import boxscoretraditionalv2

In [ ]:
# Definisci l'ID della partita di interesse
game_id = 1  # Ad esempio, puoi sostituire con l'ID della partita di cui vuoi ottenere i giocatori titolari

# Ottieni i dati della partita
boxscore = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id="0021000002")

# Ottieni i dati dei DataFrame
boxscore_data = boxscore.get_data_frames()

boxscore_data[0]

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0021000002,1610612756,PHX,Phoenix,255,Grant Hill,Grant,F,,26.000000:05,...,1.0,0.0,1.0,1.0,0.0,1.0,3.0,1.0,4.0,-8.0
1,0021000002,1610612756,PHX,Phoenix,2045,Hedo Turkoglu,Hedo,F,,27.000000:13,...,0.0,3.0,3.0,2.0,1.0,0.0,1.0,5.0,6.0,-7.0
2,0021000002,1610612756,PHX,Phoenix,201577,Robin Lopez,Robin,C,,24.000000:50,...,3.0,3.0,6.0,0.0,0.0,1.0,1.0,0.0,5.0,0.0
3,0021000002,1610612756,PHX,Phoenix,2202,Jason Richardson,Jason,G,,35.000000:05,...,2.0,4.0,6.0,1.0,1.0,0.0,1.0,0.0,22.0,-7.0
4,0021000002,1610612756,PHX,Phoenix,959,Steve Nash,Steve,G,,35.000000:25,...,0.0,3.0,3.0,6.0,1.0,0.0,9.0,1.0,26.0,-7.0
5,0021000002,1610612756,PHX,Phoenix,101112,Channing Frye,Channing,,,25.000000:24,...,0.0,6.0,6.0,2.0,0.0,2.0,2.0,3.0,3.0,-19.0
6,0021000002,1610612756,PHX,Phoenix,101124,Hakim Warrick,Hakim,,,18.000000:11,...,0.0,2.0,2.0,1.0,0.0,0.0,1.0,2.0,10.0,-2.0
7,0021000002,1610612756,PHX,Phoenix,201162,Jared Dudley,Jared,,,18.000000:18,...,1.0,2.0,3.0,1.0,0.0,0.0,1.0,4.0,6.0,-2.0
8,0021000002,1610612756,PHX,Phoenix,2735,Josh Childress,Josh,,,16.000000:54,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,-11.0
9,0021000002,1610612756,PHX,Phoenix,201609,Goran Dragic,Goran,,,12.000000:35,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,6.0,-7.0
10,0021000002,1610612756,PHX,Phoenix,201947,Earl Clark,Earl,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0021000002,1610612756,PHX,Phoenix,202081,Garret Siler,Garret,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0021000002,1610612757,POR,Portland,201587,Nicolas Batum,Nicolas,F,,26.000000:47,...,5.0,6.0,11.0,1.0,1.0,0.0,2.0,3.0,19.0,10.0
13,0021000002,1610612757,POR,Portland,200746,LaMarcus Aldridge,LaMarcus,F,,38.000000:17,...,3.0,6.0,9.0,3.0,2.0,1.0,2.0,3.0,8.0,5.0
14,0021000002,1610612757,POR,Portland,948,Marcus Camby,Marcus,C,,30.000000:02,...,4.0,6.0,10.0,3.0,1.0,1.0,1.0,2.0,13.0,5.0
15,0021000002,1610612757,POR,Portland,200750,Brandon Roy,Brandon,G,,39.000000:48,...,1.0,2.0,3.0,6.0,3.0,0.0,2.0,2.0,24.0,14.0
16,0021000002,1610612757,POR,Portland,1889,Andre Miller,Andre,G,,26.000000:42,...,2.0,0.0,2.0,9.0,1.0,0.0,3.0,1.0,10.0,14.0
17,0021000002,1610612757,POR,Portland,202083,Wesley Matthews,Wesley,,,30.000000:24,...,2.0,4.0,6.0,3.0,0.0,0.0,0.0,4.0,13.0,22.0
18,0021000002,1610612757,POR,Portland,201164,Rudy Fernandez,Rudy,,,21.000000:50,...,0.0,2.0,2.0,3.0,3.0,0.0,0.0,2.0,7.0,-3.0
19,0021000002,1610612757,POR,Portland,201967,Dante Cunningham,Dante,,,13.000000:44,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,6.0,-2.0
20,0021000002,1610612757,POR,Portland,101177,Fabricio Oberto,Fabricio,,,3.000000:03,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0
21,0021000002,1610612757,POR,Portland,202356,Armon Johnson,Armon,,,9.000000:23,...,0.0,2.0,2.0,3.0,0.0,0.0,1.0,3.0,6.0,5.0
22,0021000002,1610612757,POR,Portland,202337,Luke Babbitt,Luke,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0021000002,1610612757,POR,Portland,201988,Patty Mills,Patty,,DNP - Coach's Decision,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
boxscore_data[0].columns

Index(['GAME_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID',
       'PLAYER_NAME', 'NICKNAME', 'START_POSITION', 'COMMENT', 'MIN', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF', 'PTS',
       'PLUS_MINUS'],
      dtype='object')

In [ ]:
non_null_start_positions = boxscore_data[0][boxscore_data[0]["START_POSITION"].apply(lambda x: len(x) != 0)]

# Stampa i valori non nulli della colonna 'START_POSITION'
non_null_start_positions

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,MIN,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0021000002,1610612756,PHX,Phoenix,255,Grant Hill,Grant,F,,26.000000:05,...,1.0,0.0,1.0,1.0,0.0,1.0,3.0,1.0,4.0,-8.0
1,0021000002,1610612756,PHX,Phoenix,2045,Hedo Turkoglu,Hedo,F,,27.000000:13,...,0.0,3.0,3.0,2.0,1.0,0.0,1.0,5.0,6.0,-7.0
2,0021000002,1610612756,PHX,Phoenix,201577,Robin Lopez,Robin,C,,24.000000:50,...,3.0,3.0,6.0,0.0,0.0,1.0,1.0,0.0,5.0,0.0
3,0021000002,1610612756,PHX,Phoenix,2202,Jason Richardson,Jason,G,,35.000000:05,...,2.0,4.0,6.0,1.0,1.0,0.0,1.0,0.0,22.0,-7.0
4,0021000002,1610612756,PHX,Phoenix,959,Steve Nash,Steve,G,,35.000000:25,...,0.0,3.0,3.0,6.0,1.0,0.0,9.0,1.0,26.0,-7.0
12,0021000002,1610612757,POR,Portland,201587,Nicolas Batum,Nicolas,F,,26.000000:47,...,5.0,6.0,11.0,1.0,1.0,0.0,2.0,3.0,19.0,10.0
13,0021000002,1610612757,POR,Portland,200746,LaMarcus Aldridge,LaMarcus,F,,38.000000:17,...,3.0,6.0,9.0,3.0,2.0,1.0,2.0,3.0,8.0,5.0
14,0021000002,1610612757,POR,Portland,948,Marcus Camby,Marcus,C,,30.000000:02,...,4.0,6.0,10.0,3.0,1.0,1.0,1.0,2.0,13.0,5.0
15,0021000002,1610612757,POR,Portland,200750,Brandon Roy,Brandon,G,,39.000000:48,...,1.0,2.0,3.0,6.0,3.0,0.0,2.0,2.0,24.0,14.0
16,0021000002,1610612757,POR,Portland,1889,Andre Miller,Andre,G,,26.000000:42,...,2.0,0.0,2.0,9.0,1.0,0.0,3.0,1.0,10.0,14.0

In [ ]:
def titolari(game_id):
    # Ottieni i dati della partita
    boxscore = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=game_id)

    # Ottieni i dati dei DataFrame
    boxscore_data = boxscore.get_data_frames()

    start_positions = boxscore_data[0][boxscore_data[0]["START_POSITION"].apply(lambda x: len(x) != 0)]
    
    return start_positions

In [ ]:

for index,row in final_df.iterrows():
    start_pos = titolari (row["GAME_ID"])
    print(f"Titolari game_id: {row['GAME_ID']} tra {row['MATCHUP']} del {row['GAME_DATE']}")
    print(start_pos["PLAYER_NAME"].to_list())
    print()

Titolari game_id: 0022000302 tra LAL @ BOS del 2021-01-30
['LeBron James', 'Anthony Davis', 'Marc Gasol', 'Kentavious Caldwell-Pope', 'Dennis Schroder', 'Jaylen Brown', 'Jayson Tatum', 'Daniel Theis', 'Marcus Smart', 'Kemba Walker']

Titolari game_id: 0022000842 tra LAL vs. BOS del 2021-04-15
['Jayson Tatum', 'Jaylen Brown', 'Tristan Thompson', 'Marcus Smart', 'Kemba Walker', 'Wesley Matthews', 'Kyle Kuzma', 'Marc Gasol', 'Kentavious Caldwell-Pope', 'Dennis Schroder']

Titolari game_id: 0022100232 tra LAL @ BOS del 2021-11-19
['Talen Horton-Tucker', 'LeBron James', 'Anthony Davis', 'Avery Bradley', 'Russell Westbrook', 'Jayson Tatum', 'Grant Williams', 'Al Horford', 'Dennis Schroder', 'Marcus Smart']

Titolari game_id: 0022100365 tra LAL vs. BOS del 2021-12-07
['Jayson Tatum', 'Al Horford', 'Robert Williams III', 'Marcus Smart', 'Dennis Schroder', 'Talen Horton-Tucker', 'LeBron James', 'Anthony Davis', 'Avery Bradley', 'Russell Westbrook']

Titolari game_id: 0022200413 tra LAL vs. BOS del 2022-12-13
['Jaylen Brown', 'Jayson Tatum', 'Blake Griffin', 'Derrick White', 'Marcus Smart', 'Lonnie Walker IV', 'LeBron James', 'Anthony Davis', 'Patrick Beverley', 'Dennis Schroder']

Titolari game_id: 0022200749 tra LAL @ BOS del 2023-01-28
['Troy Brown Jr.', 'LeBron James', 'Thomas Bryant', 'Patrick Beverley', 'Dennis Schroder', 'Jayson Tatum', 'Grant Williams', 'Al Horford', 'Jaylen Brown', 'Derrick White']

Titolari game_id: 0022300403 tra LAL vs. BOS del 2023-12-25
['Jaylen Brown', 'Jayson Tatum', 'Kristaps Porzingis', 'Derrick White', 'Jrue Holiday', 'Cam Reddish', 'Jarred Vanderbilt', 'Anthony Davis', 'Taurean Prince', 'LeBron James']

Titolari game_id: 0022300684 tra LAL @ BOS del 2024-02-01
['Taurean Prince', 'Jarred Vanderbilt', 'Jaxson Hayes', 'Austin Reaves', "D'Angelo Russell", 'Jaylen Brown', 'Jayson Tatum', 'Kristaps Porzingis', 'Derrick White', 'Jrue Holiday']

In [ ]:
start_pos[start_pos["TEAM_ABBREVIATION"] == "PHX"]["PLAYER_NAME"].to_list()

['Grant Hill',
 'Hedo Turkoglu',
 'Robin Lopez',
 'Jason Richardson',
 'Steve Nash']

In [ ]:
# for index,row in final_df.iterrows():
#     start_pos = titolari (row["GAME_ID"])
#     #print(start_pos)
#     print(f"Titolari game_id: {row['GAME_ID']} tra {row['MATCHUP']} del {row['GAME_DATE']}")
#     print(start_pos["PLAYER_NAME"].to_list())
#     print()

In [ ]:
for index,row in final_df.iterrows():
    start_pos = titolari(row["GAME_ID"])
    #print(f"{type(row['GAME_ID'])} - {row['GAME_ID']}")
    print(f"Titolari game_id: {row['GAME_ID']} tra {row['MATCHUP']} del {row['GAME_DATE']}")
    print(f"Squadra: {row['MATCHUP'].split(' ')[0].strip()}")
    print(start_pos[start_pos["TEAM_ABBREVIATION"] == row['MATCHUP'].split(" ")[0]]["PLAYER_NAME"].to_list())
    print(f"Squadra: {row['MATCHUP'].split(' ')[-1]}")
    print(start_pos[start_pos["TEAM_ABBREVIATION"] == row['MATCHUP'].split(" ")[-1]]["PLAYER_NAME"].to_list())
    print()

Titolari game_id: 0022000302 tra LAL @ BOS del 2021-01-30
Squadra: LAL
['LeBron James', 'Anthony Davis', 'Marc Gasol', 'Kentavious Caldwell-Pope', 'Dennis Schroder']
Squadra: BOS
['Jaylen Brown', 'Jayson Tatum', 'Daniel Theis', 'Marcus Smart', 'Kemba Walker']

Titolari game_id: 0022000842 tra LAL vs. BOS del 2021-04-15
Squadra: LAL
['Wesley Matthews', 'Kyle Kuzma', 'Marc Gasol', 'Kentavious Caldwell-Pope', 'Dennis Schroder']
Squadra: BOS
['Jayson Tatum', 'Jaylen Brown', 'Tristan Thompson', 'Marcus Smart', 'Kemba Walker']

Titolari game_id: 0022100232 tra LAL @ BOS del 2021-11-19
Squadra: LAL
['Talen Horton-Tucker', 'LeBron James', 'Anthony Davis', 'Avery Bradley', 'Russell Westbrook']
Squadra: BOS
['Jayson Tatum', 'Grant Williams', 'Al Horford', 'Dennis Schroder', 'Marcus Smart']

Titolari game_id: 0022100365 tra LAL vs. BOS del 2021-12-07
Squadra: LAL
['Talen Horton-Tucker', 'LeBron James', 'Anthony Davis', 'Avery Bradley', 'Russell Westbrook']
Squadra: BOS
['Jayson Tatum', 'Al Horford', 'Robert Williams III', 'Marcus Smart', 'Dennis Schroder']

Titolari game_id: 0022200413 tra LAL vs. BOS del 2022-12-13
Squadra: LAL
['Lonnie Walker IV', 'LeBron James', 'Anthony Davis', 'Patrick Beverley', 'Dennis Schroder']
Squadra: BOS
['Jaylen Brown', 'Jayson Tatum', 'Blake Griffin', 'Derrick White', 'Marcus Smart']

Titolari game_id: 0022200749 tra LAL @ BOS del 2023-01-28
Squadra: LAL
['Troy Brown Jr.', 'LeBron James', 'Thomas Bryant', 'Patrick Beverley', 'Dennis Schroder']
Squadra: BOS
['Jayson Tatum', 'Grant Williams', 'Al Horford', 'Jaylen Brown', 'Derrick White']

Titolari game_id: 0022300403 tra LAL vs. BOS del 2023-12-25
Squadra: LAL
['Cam Reddish', 'Jarred Vanderbilt', 'Anthony Davis', 'Taurean Prince', 'LeBron James']
Squadra: BOS
['Jaylen Brown', 'Jayson Tatum', 'Kristaps Porzingis', 'Derrick White', 'Jrue Holiday']

Titolari game_id: 0022300684 tra LAL @ BOS del 2024-02-01
Squadra: LAL
['Taurean Prince', 'Jarred Vanderbilt', 'Jaxson Hayes', 'Austin Reaves', "D'Angelo Russell"]
Squadra: BOS
['Jaylen Brown', 'Jayson Tatum', 'Kristaps Porzingis', 'Derrick White', 'Jrue Holiday']

# Other

In [ ]:
from nba_api.stats.endpoints import playbyplayv2

# Definisci l'ID della partita di interesse
game_id = '0022000612'  # Puoi sostituire con l'ID della partita di cui vuoi ottenere gli arbitri

# Ottieni i dati del resoconto della partita
play_by_play = playbyplayv2.PlayByPlayV2(game_id=game_id)

# Ottieni i dati dei DataFrame
play_by_play_data = play_by_play.get_data_frames()

# Estrai il nome degli arbitri
# referees = play_by_play_data[0]['PlayByPlay']

# # Stampiamo i nomi degli arbitri
# print(referees['HOME_TEAM_REVIEW', 'AWAY_TEAM_REVIEW'])
play_by_play_data[0].columns

Index(['GAME_ID', 'EVENTNUM', 'EVENTMSGTYPE', 'EVENTMSGACTIONTYPE', 'PERIOD',
       'WCTIMESTRING', 'PCTIMESTRING', 'HOMEDESCRIPTION', 'NEUTRALDESCRIPTION',
       'VISITORDESCRIPTION', 'SCORE', 'SCOREMARGIN', 'PERSON1TYPE',
       'PLAYER1_ID', 'PLAYER1_NAME', 'PLAYER1_TEAM_ID', 'PLAYER1_TEAM_CITY',
       'PLAYER1_TEAM_NICKNAME', 'PLAYER1_TEAM_ABBREVIATION', 'PERSON2TYPE',
       'PLAYER2_ID', 'PLAYER2_NAME', 'PLAYER2_TEAM_ID', 'PLAYER2_TEAM_CITY',
       'PLAYER2_TEAM_NICKNAME', 'PLAYER2_TEAM_ABBREVIATION', 'PERSON3TYPE',
       'PLAYER3_ID', 'PLAYER3_NAME', 'PLAYER3_TEAM_ID', 'PLAYER3_TEAM_CITY',
       'PLAYER3_TEAM_NICKNAME', 'PLAYER3_TEAM_ABBREVIATION',
       'VIDEO_AVAILABLE_FLAG'],
      dtype='object')

In [ ]:
play_by_play_data[0]

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,...,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG
0,0022000612,2,12,0,1,8:11 PM,12:00,None,Start of 1st Period (8:11 PM EST),None,...,None,None,0,0,None,NaN,None,None,None,0
1,0022000612,4,10,0,1,8:11 PM,12:00,Jump Ball Markkanen vs. Brown: Tip to Gilgeous...,None,None,...,Thunder,OKC,5,1628983,Shai Gilgeous-Alexander,1.610613e+09,Oklahoma City,Thunder,OKC,1
2,0022000612,7,2,101,1,8:11 PM,11:44,None,None,MISS Maledon 2' Driving Floating Jump Shot,...,None,None,0,0,None,NaN,None,None,None,1
3,0022000612,8,4,0,1,8:11 PM,11:41,Satoransky REBOUND (Off:0 Def:1),None,None,...,None,None,0,0,None,NaN,None,None,None,1
4,0022000612,9,1,2,1,8:11 PM,11:39,Markkanen 26' 3PT Running Jump Shot (3 PTS) (S...,None,None,...,Bulls,CHI,0,0,None,NaN,None,None,None,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,0022000612,634,4,0,4,10:14 PM,0:41,Gafford REBOUND (Off:2 Def:0),None,None,...,None,None,0,0,None,NaN,None,None,None,1
440,0022000612,635,1,72,4,10:14 PM,0:41,Gafford 1' Putback Layup (2 PTS),None,None,...,None,None,0,0,None,NaN,None,None,None,1
441,0022000612,636,1,9,4,10:14 PM,0:31,None,None,Roby Driving Dunk (11 PTS),...,None,None,0,0,None,NaN,None,None,None,1
442,0022000612,637,5,11,4,10:15 PM,0:07,BULLS Turnover: Shot Clock (T#12),None,None,...,None,None,1,0,None,NaN,None,None,None,0
443,0022000612,638,13,0,4,10:15 PM,0:00,None,End of 4th Period (10:15 PM EST),None,...,None,None,0,0,None,NaN,None,None,None,1

In [ ]:
from nba_api.stats.endpoints import boxscoreplayertrackv2

game_id = '0022000612'  # Sostituisci con l'ID della partita di interesse
player_tracking = boxscoreplayertrackv2.BoxScorePlayerTrackV2(game_id=game_id)
player_tracking_data = player_tracking.get_data_frames()

player_tracking_data[0].columns

Index(['GAME_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID',
       'PLAYER_NAME', 'START_POSITION', 'COMMENT', 'MIN', 'SPD', 'DIST',
       'ORBC', 'DRBC', 'RBC', 'TCHS', 'SAST', 'FTAST', 'PASS', 'AST', 'CFGM',
       'CFGA', 'CFG_PCT', 'UFGM', 'UFGA', 'UFG_PCT', 'FG_PCT', 'DFGM', 'DFGA',
       'DFG_PCT'],
      dtype='object')

# Fantasy points

In [51]:
from nba_api.stats.endpoints import playerdashboardbylastngames

# Definisci l'ID del giocatore di interesse
player_id = '2544'  # Ad esempio, questo Ã¨ l'ID di Lebron
num_games = 100  # Numero di partite da considerare

# Ottieni le statistiche del giocatore per gli ultimi giochi specificati
player_dashboard = playerdashboardbylastngames.PlayerDashboardByLastNGames(player_id=player_id)

# Ottieni i dati dei DataFrame
player_dashboard_data = player_dashboard.get_data_frames()

# Estrai le statistiche del giocatore
player_stats = player_dashboard_data[0]

# Calcola i fantasy points utilizzando le statistiche disponibili e i coefficienti appropriati
coeff_pts = 1.0
coeff_reb = 1.0
coeff_ast = 1.0
coeff_stl = 2.0
coeff_blk = 2.0
coeff_to = -1.0

# fantasy_points = (player_stats['PTS'] * coeff_pts +
#                   player_stats['REB'] * coeff_reb +
#                   player_stats['AST'] * coeff_ast +
#                   player_stats['STL'] * coeff_stl +
#                   player_stats['BLK'] * coeff_blk +
#                   player_stats['TO'] * coeff_to)

# print("Fantasy Points:", fantasy_points)

In [52]:
player_dashboard_data[0]

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK
0,Overall,2023-24,60,32,28,0.533,2106.086667,576,1082,0.532,...,1,1,1,1,1,1,1,1,1,1

In [31]:
player_dashboard_data[0].columns

Index(['GROUP_SET', 'GROUP_VALUE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD',
       'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS', 'DD2', 'TD3',
       'WNBA_FANTASY_PTS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK',
       'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK',
       'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK',
       'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK',
       'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK',
       'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK', 'TD3_RANK',
       'WNBA_FANTASY_PTS_RANK'],
      dtype='object')

In [54]:
from nba_api.stats.endpoints import playercareerstats

# Nikola JokiÄ‡
career = playercareerstats.PlayerCareerStats(player_id='203999')

# pandas data frames (optional: pip install pandas)
player_stats = career.get_data_frames()[0]

# Calcola i fantasy points utilizzando le statistiche disponibili e i coefficienti appropriati
coeff_pts = 1.0
coeff_reb = 1.2
coeff_ast = 1.5
coeff_stl = 3.0
coeff_blk = 3.0
coeff_to = -1.0

fantasy_points = (player_stats['PTS'] * coeff_pts +
                  player_stats['REB'] * coeff_reb +
                  player_stats['AST'] * coeff_ast +
                  player_stats['STL'] * coeff_stl +
                  player_stats['BLK'] * coeff_blk +
                  player_stats['TOV'] * coeff_to)

print("Fantasy Points:")
fantasy_points

Fantasy Points:

0    2034.5
1    2798.1
2    3278.6
3    3753.0
4    3238.2
5    3939.5
6    4337.8
7    3842.4
8    3866.2
dtype: float64

In [56]:
from nba_api.stats.endpoints import playercareerstats

def get_FP_player(player_id):

    career = playercareerstats.PlayerCareerStats(player_id=player_id)

    # pandas data frames (optional: pip install pandas)
    player_stats = career.get_data_frames()[0]

    # Calcola i fantasy points utilizzando le statistiche disponibili e i coefficienti appropriati
    coeff_pts = 1.0
    coeff_reb = 1.2
    coeff_ast = 1.5
    coeff_stl = 3.0
    coeff_blk = 3.0
    coeff_to = -1.0

    fantasy_points = (player_stats['PTS'] * coeff_pts +
                    player_stats['REB'] * coeff_reb +
                    player_stats['AST'] * coeff_ast +
                    player_stats['STL'] * coeff_stl +
                    player_stats['BLK'] * coeff_blk +
                    player_stats['TOV'] * coeff_to)
    ## ritorno solo il FP dell'ultima season
    return fantasy_points.iloc[-1]

In [64]:
get_FP_player(2544).iloc[-1]

2900.7

In [60]:
playercareerstats.PlayerCareerStats(player_id=2544).get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,3120.0,622,...,0.754,99,333,432,465,130,58,273,149,1654
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,3388.0,795,...,0.750,111,477,588,577,177,52,262,146,2175
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,3361.0,875,...,0.738,75,481,556,521,123,66,260,181,2478
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,3190.0,772,...,0.698,83,443,526,470,125,55,250,171,2132
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,3027.0,794,...,0.712,133,459,592,539,138,81,255,165,2250
5,2544,2008-09,00,1610612739,CLE,24.0,81,81,3054.0,789,...,0.780,106,507,613,587,137,93,241,139,2304
6,2544,2009-10,00,1610612739,CLE,25.0,76,76,2966.0,768,...,0.767,71,483,554,651,125,77,261,119,2258
7,2544,2010-11,00,1610612748,MIA,26.0,79,79,3063.0,758,...,0.759,80,510,590,554,124,50,284,163,2111
8,2544,2011-12,00,1610612748,MIA,27.0,62,62,2326.0,621,...,0.771,94,398,492,387,115,50,213,96,1683
9,2544,2012-13,00,1610612748,MIA,28.0,76,76,2877.0,765,...,0.753,97,513,610,551,129,67,226,110,2036
10,2544,2013-14,00,1610612748,MIA,29.0,77,77,2902.0,767,...,0.750,81,452,533,488,121,26,270,126,2089
11,2544,2014-15,00,1610612739,CLE,30.0,69,69,2493.0,624,...,0.710,51,365,416,511,109,49,272,135,1743
12,2544,2015-16,00,1610612739,CLE,31.0,76,76,2709.0,737,...,0.731,111,454,565,514,104,49,249,143,1920
13,2544,2016-17,00,1610612739,CLE,32.0,74,74,2795.0,736,...,0.674,97,542,639,646,92,44,303,134,1954
14,2544,2017-18,00,1610612739,CLE,33.0,82,82,3026.0,857,...,0.731,97,612,709,747,116,71,347,136,2251
15,2544,2018-19,00,1610612747,LAL,34.0,55,55,1937.0,558,...,0.665,57,408,465,454,72,33,197,94,1505
16,2544,2019-20,00,1610612747,LAL,35.0,67,67,2316.0,643,...,0.693,66,459,525,684,78,36,261,118,1698
17,2544,2020-21,00,1610612747,LAL,36.0,45,45,1504.0,422,...,0.698,29,317,346,350,48,25,168,70,1126
18,2544,2021-22,00,1610612747,LAL,37.0,56,56,2084.0,640,...,0.756,63,396,459,349,73,59,196,121,1695
19,2544,2022-23,00,1610612747,LAL,38.0,55,54,1954.0,609,...,0.768,65,392,457,375,50,32,178,88,1590
20,2544,2023-24,00,1610612747,LAL,39.0,60,60,2106.0,576,...,0.746,51,380,431,485,74,34,195,70,1527

# Metodi previsione

In [77]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Carica il dataset fittizio
# Supponiamo che il dataset contenga le statistiche di gioco di due squadre e il risultato della partita
data = {
    'Team1_Points': [102, 110, 95, 98, 115, 107, 105, 112, 100, 104],
    'Team1_Assists': [20, 22, 18, 19, 23, 21, 20, 24, 19, 20],
    'Team1_Rebounds': [40, 42, 38, 39, 43, 41, 40, 44, 39, 40],
    'Team2_Points': [98, 102, 97, 105, 100, 99, 103, 107, 101, 98],
    'Team2_Assists': [18, 20, 17, 21, 19, 18, 20, 22, 19, 18],
    'Team2_Rebounds': [38, 40, 37, 41, 39, 38, 40, 42, 39, 38],
    'Result': [1, 1, 0, 1, 1, 0, 1, 1, 0, 1]  # 1: squadra di casa vince, 0: squadra di casa perde
}

df = pd.DataFrame(data)

# Dividi il dataset in set di addestramento e di test
X = df.drop('Result', axis=1)
y = df['Result']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Addestra il modello di regressione logistica
model = LogisticRegression()
model.fit(X_train, y_train)

# Effettua le previsioni sul set di test
predictions = model.predict(X_test)

# Valuta l'accuratezza del modello
accuracy = accuracy_score(y_test, predictions) * 100
print("Accuratezza del modello:", accuracy)

Accuratezza del modello: 50.0

In [80]:
from nba_api.stats.endpoints import boxscoretraditionalv2

# Funzione per estrarre i nomi degli arbitri da un oggetto boxscoretraditionalv2
def extract_referees(boxscore):
    referees = []
    for i in range(len(boxscore.referees)):
        referee = boxscore.referees[i].strip()
        referees.append(referee)
    return referees

# Definisci la partita di cui vuoi estrarre gli arbitri
game_id = '0022000001'  # Sostituisci con il Game ID della partita desiderata

# Ottieni i dati del boxscore tradizionale della partita
boxscore_traditional = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=game_id)


# Estrai i nomi degli arbitri
referees = extract_referees(boxscore_traditional)

# Stampiamo i nomi degli arbitri
print("Arbitri della partita:")
for referee in referees:
    print(referee)

AttributeError: 'BoxScoreTraditionalV2' object has no attribute 'referees'

In [82]:
# Definisci la partita di cui vuoi estrarre gli arbitri
game_id = '0022000001'  # Sostituisci con il Game ID della partita desiderata

# Ottieni i dati del boxscore tradizionale della partita
boxscoretraditionalv2.BoxScoreTraditionalV2(game_id=game_id).get_data_frames()[0].columns

Index(['GAME_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID',
       'PLAYER_NAME', 'NICKNAME', 'START_POSITION', 'COMMENT', 'MIN', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF', 'PTS',
       'PLUS_MINUS'],
      dtype='object')

In [90]:
from nba_api.stats.endpoints import playbyplayv2
game_id = '0022000001'  # Sostituisci con il Game ID della partita desiderata

# Ottieni i dati del play-by-play della partita
playbyplayv2.PlayByPlayV2(game_id).get_data_frames()[0]['HOMEDESCRIPTION']

0                                                   None
1
2      Jordan Out of Bounds - Bad Pass Turnover Turno...
3                    Irving S.FOUL (P1.T1) (S.Twardoski)
4                                                   None
                             ...
512    Brown Out of Bounds - Bad Pass Turnover Turnov...
513                                                 None
514                                                 None
515                                                 None
516                                                 None
Name: HOMEDESCRIPTION, Length: 517, dtype: object

In [102]:
from datetime import datetime
from nba_api.stats.endpoints import LeagueGameFinder

# Ottieni la data attuale
current_date = datetime.now()
current_season = current_date.year if current_date.month >= 10 else current_date.year - 1


# Cerca tutte le partite future
game_finder = LeagueGameFinder(date_from_nullable="03/26/2024")
game_finder.get_data_frames()[0]

Empty DataFrame
Columns: [SEASON_ID, TEAM_ID, TEAM_ABBREVIATION, TEAM_NAME, GAME_ID, GAME_DATE, MATCHUP, WL, MIN, PTS, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PLUS_MINUS]
Index: []

[0 rows x 28 columns]

In [95]:
from datetime import datetime
from nba_api.stats.static import teams
from nba_api.stats.endpoints import LeagueGameFinder

# Ottieni la data attuale
current_date = datetime.now().strftime("%m/%d/%Y")

# Ottieni l'ID della stagione corrente
current_season = datetime.now().year

# Ottieni l'elenco delle squadre NBA
nba_teams = teams.get_teams()

# Inizializza una lista per memorizzare le partite future
future_games = []

# Itera su ogni squadra per ottenere le partite future
for team in nba_teams:
    team_id = team['id']
    game_finder = LeagueGameFinder(team_id_nullable=team_id, date_to_nullable="12/12/2024", league_id_nullable='00')
    games = game_finder.get_data_frames()[0]
    future_games.append(games)

# Concatena tutti i DataFrame delle partite future
all_future_games = pd.concat(future_games)

# Stampa le partite future del campionato corrente
print(all_future_games)

     SEASON_ID     TEAM_ID TEAM_ABBREVIATION          TEAM_NAME     GAME_ID  \
0        22023  1610612737               ATL      Atlanta Hawks  0022301034
1        22023  1610612737               ATL      Atlanta Hawks  0022301021
2        22023  1610612737               ATL      Atlanta Hawks  0022301010
3        22023  1610612737               ATL      Atlanta Hawks  0022300990
4        22023  1610612737               ATL      Atlanta Hawks  0022300982
...        ...         ...               ...                ...         ...
2885     21988  1610612766               CHH  Charlotte Hornets  0028800062
2886     21988  1610612766               CHH  Charlotte Hornets  0028800052
2887     21988  1610612766               CHH  Charlotte Hornets  0028800024
2888     21988  1610612766               CHH  Charlotte Hornets  0028800015
2889     21988  1610612766               CHH  Charlotte Hornets  0028800008

       GAME_DATE      MATCHUP WL  MIN  PTS  ...  FT_PCT  OREB  DREB  REB  AST  \
0     2024-03-25  ATL vs. BOS  W  241  120  ...   0.588  15.0  29.0   44   30
1     2024-03-23  ATL vs. CHA  W  240  132  ...   0.857  11.0  32.0   43   40
2     2024-03-21    ATL @ PHX  L  241  115  ...   0.793  12.0  24.0   36   27
3     2024-03-18    ATL @ LAL  L  240  105  ...   0.800  12.0  30.0   42   32
4     2024-03-17    ATL @ LAC  W  240  110  ...   0.917  10.0  35.0   45   32
...          ...          ... ..  ...  ...  ...     ...   ...   ...  ...  ...
2885  1988-11-12    CHH @ ATL  L  238  111  ...   0.813  14.0  21.0   35   30
2886  1988-11-11    CHH @ WAS  L  240   87  ...   0.760  11.0  32.0   43   22
2887  1988-11-08  CHH vs. LAC  W  240  117  ...   0.738  17.0  38.0   55   28
2888  1988-11-05    CHH @ DET  L  240   85  ...   1.000  21.0  19.0   40   18
2889  1988-11-04  CHH vs. CLE  L  240   93  ...   0.650   7.0  24.0   31   27

       STL  BLK  TOV  PF  PLUS_MINUS
0      5.0    3   13  18         2.0
1      9.0    5    8  14        41.0
2     11.0    3    8  23       -13.0
3      8.0    5    9  14       -31.0
4     10.0    7   14  22        17.0
...    ...  ...  ...  ..         ...
2885  12.0    2   19  26         NaN
2886   9.0    1   23  26         NaN
2887   9.0    1   17  31         NaN
2888   8.0    6   11  21         NaN
2889   8.0    1   24  25         NaN

[102908 rows x 28 columns]

In [96]:
all_future_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22023,1610612737,ATL,Atlanta Hawks,0022301034,2024-03-25,ATL vs. BOS,W,241,120,...,0.588,15.0,29.0,44,30,5.0,3,13,18,2.0
1,22023,1610612737,ATL,Atlanta Hawks,0022301021,2024-03-23,ATL vs. CHA,W,240,132,...,0.857,11.0,32.0,43,40,9.0,5,8,14,41.0
2,22023,1610612737,ATL,Atlanta Hawks,0022301010,2024-03-21,ATL @ PHX,L,241,115,...,0.793,12.0,24.0,36,27,11.0,3,8,23,-13.0
3,22023,1610612737,ATL,Atlanta Hawks,0022300990,2024-03-18,ATL @ LAL,L,240,105,...,0.800,12.0,30.0,42,32,8.0,5,9,14,-31.0
4,22023,1610612737,ATL,Atlanta Hawks,0022300982,2024-03-17,ATL @ LAC,W,240,110,...,0.917,10.0,35.0,45,32,10.0,7,14,22,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2885,21988,1610612766,CHH,Charlotte Hornets,0028800062,1988-11-12,CHH @ ATL,L,238,111,...,0.813,14.0,21.0,35,30,12.0,2,19,26,NaN
2886,21988,1610612766,CHH,Charlotte Hornets,0028800052,1988-11-11,CHH @ WAS,L,240,87,...,0.760,11.0,32.0,43,22,9.0,1,23,26,NaN
2887,21988,1610612766,CHH,Charlotte Hornets,0028800024,1988-11-08,CHH vs. LAC,W,240,117,...,0.738,17.0,38.0,55,28,9.0,1,17,31,NaN
2888,21988,1610612766,CHH,Charlotte Hornets,0028800015,1988-11-05,CHH @ DET,L,240,85,...,1.000,21.0,19.0,40,18,8.0,6,11,21,NaN
2889,21988,1610612766,CHH,Charlotte Hornets,0028800008,1988-11-04,CHH vs. CLE,L,240,93,...,0.650,7.0,24.0,31,27,8.0,1,24,25,NaN

In [107]:
from nba_api.stats.endpoints import leaguegamefinder
gamefinder = leaguegamefinder.LeagueGameFinder(season_nullable = "2023-24")
gamefinder.get_data_frames()[0]

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22023,1610612747,LAL,Los Angeles Lakers,0022301045,2024-03-26,LAL @ MIL,W,290,128,...,0.938,15,54,69,30,4,8,17,13,4.0
1,22023,1612709890,AUS,Austin Spurs,2022300492,2024-03-26,AUS @ SLC,L,242,108,...,0.750,7,35,42,30,7,6,9,15,-8.6
2,22023,1610612749,MIL,Milwaukee Bucks,0022301045,2024-03-26,MIL vs. LAL,L,289,124,...,0.647,15,46,61,37,9,5,14,26,-4.0
3,22023,1612709926,MHU,Memphis Hustle,2022300491,2024-03-26,MHU vs. STO,W,242,118,...,0.667,6,34,40,26,6,2,17,18,-2.4
4,22023,1612709903,SLC,Salt Lake City Stars,2022300492,2024-03-26,SLC vs. AUS,W,239,113,...,0.750,14,43,57,30,5,8,17,11,6.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3800,12023,1612709930,GLI,G League Ignite,2012300002,2023-09-08,GLI vs. PER,L,240,112,...,0.829,17,25,42,24,12,10,17,29,-15.0
3801,12023,104,PER,Perth Wildcats,2012300001,2023-09-06,PER @ GLI,L,239,105,...,0.846,21,19,40,27,13,8,21,21,-19.0
3802,12023,1612709930,GLI,G League Ignite,2012300001,2023-09-06,GLI vs. PER,W,240,124,...,0.870,11,32,43,27,12,10,22,23,19.0
3803,22023,54,PUR,Puerto Rico Puerto Rico,1722300001,2023-08-07,PUR @ USA,L,199,74,...,0.722,7,20,27,14,8,2,17,20,-30.2
3804,22023,40,USA,United States United States,1722300001,2023-08-07,USA vs. PUR,W,200,117,...,0.625,14,39,53,29,10,10,11,15,31.6

In [110]:
season = '2023-24'

# Ottieni il log delle partite per la stagione specificata
gamelog = leaguegamelog.LeagueGameLog(season=season)
gamelog.get_data_frames()[0]

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22023,1610612747,LAL,Los Angeles Lakers,0022300061,2023-10-24,LAL @ DEN,L,240,41,...,31,44,23,5,4,12,18,107,-12,1
1,22023,1610612743,DEN,Denver Nuggets,0022300061,2023-10-24,DEN vs. LAL,W,240,48,...,33,42,29,9,6,12,15,119,12,1
2,22023,1610612756,PHX,Phoenix Suns,0022300062,2023-10-24,PHX @ GSW,W,240,42,...,43,60,23,5,7,19,22,108,4,1
3,22023,1610612744,GSW,Golden State Warriors,0022300062,2023-10-24,GSW vs. PHX,L,240,36,...,31,49,19,11,6,11,23,104,-4,1
4,22023,1610612746,LAC,LA Clippers,0022300074,2023-10-25,LAC vs. POR,W,240,47,...,31,45,36,11,7,18,20,123,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2147,22023,1610612749,MIL,Milwaukee Bucks,0022301045,2024-03-26,MIL vs. LAL,L,290,49,...,46,61,37,9,5,14,26,124,-4,1
2148,22023,1610612760,OKC,Oklahoma City Thunder,0022301046,2024-03-26,OKC @ NOP,W,240,46,...,38,45,28,5,3,12,17,119,7,1
2149,22023,1610612740,NOP,New Orleans Pelicans,0022301046,2024-03-26,NOP vs. OKC,L,240,39,...,32,37,26,7,2,10,18,112,-7,1
2150,22023,1610612744,GSW,Golden State Warriors,0022301044,2024-03-26,GSW @ MIA,W,240,47,...,36,43,31,6,5,12,20,113,21,1
2151,22023,1610612748,MIA,Miami Heat,0022301044,2024-03-26,MIA vs. GSW,L,240,37,...,28,39,24,3,2,9,9,92,-21,1

In [122]:
from nba_api.live.nba.endpoints import scoreboard

# Today's Score Board
games = scoreboard.ScoreBoard().get_data_frames()[0]
games
# dictio = games.get_dict()
# ww = pd.DataFrame(dictio)
# ww

AttributeError: 'ScoreBoard' object has no attribute 'get_data_frames'

In [116]:
games.get_json()

'{"meta": {"version": 1, "request": "https://nba-prod-us-east-1-mediaops-stats.s3.amazonaws.com/NBA/liveData/scoreboard/todaysScoreboard_00.json", "time": "2024-03-27 03:30:20.3020", "code": 200}, "scoreboard": {"gameDate": "2024-03-26", "leagueId": "00", "leagueName": "National Basketball Association", "games": [{"gameId": "0022301044", "gameCode": "20240326/GSWMIA", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2024-03-26T23:30:00Z", "gameEt": "2024-03-26T19:30:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "gameLabel": "", "gameSubLabel": "", "seriesText": "", "seriesConference": "", "poRoundDesc": "", "gameSubtype": "", "homeTeam": {"teamId": 1610612748, "teamName": "Heat", "teamCity": "Miami", "teamTricode": "MIA", "wins": 39, "losses": 33, "score": 92, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 26}, {"period": 2, "periodType": "REGULAR", "score": 29}, {"period": 3, "periodType": "REGULAR", "score": 20}, {"period": 4, "periodType": "REGULAR", "score": 17}]}, "awayTeam": {"teamId": 1610612744, "teamName": "Warriors", "teamCity": "Golden State", "teamTricode": "GSW", "wins": 37, "losses": 34, "score": 113, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 24}, {"period": 2, "periodType": "REGULAR", "score": 29}, {"period": 3, "periodType": "REGULAR", "score": 32}, {"period": 4, "periodType": "REGULAR", "score": 28}]}, "gameLeaders": {"homeLeaders": {"personId": 1628389, "name": "Bam Adebayo", "jerseyNum": "13", "position": "C-F", "teamTricode": "MIA", "playerSlug": null, "points": 24, "rebounds": 9, "assists": 5}, "awayLeaders": {"personId": 202691, "name": "Klay Thompson", "jerseyNum": "11", "position": "G", "teamTricode": "GSW", "playerSlug": null, "points": 28, "rebounds": 5, "assists": 2}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}, {"gameId": "0022301045", "gameCode": "20240326/LALMIL", "gameStatus": 3, "gameStatusText": "Final/OT2", "period": 6, "gameClock": "", "gameTimeUTC": "2024-03-26T23:30:00Z", "gameEt": "2024-03-26T19:30:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "gameLabel": "", "gameSubLabel": "", "seriesText": "", "seriesConference": "", "poRoundDesc": "", "gameSubtype": "", "homeTeam": {"teamId": 1610612749, "teamName": "Bucks", "teamCity": "Milwaukee", "teamTricode": "MIL", "wins": 46, "losses": 26, "score": 124, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 32}, {"period": 2, "periodType": "REGULAR", "score": 26}, {"period": 3, "periodType": "REGULAR", "score": 30}, {"period": 4, "periodType": "REGULAR", "score": 13}, {"period": 5, "periodType": "OVERTIME", "score": 16}, {"period": 6, "periodType": "OVERTIME", "score": 7}]}, "awayTeam": {"teamId": 1610612747, "teamName": "Lakers", "teamCity": "Los Angeles", "teamTricode": "LAL", "wins": 40, "losses": 32, "score": 128, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 16}, {"period": 2, "periodType": "REGULAR", "score": 26}, {"period": 3, "periodType": "REGULAR", "score": 32}, {"period": 4, "periodType": "REGULAR", "score": 27}, {"period": 5, "periodType": "OVERTIME", "score": 16}, {"period": 6, "periodType": "OVERTIME", "score": 11}]}, "gameLeaders": {"homeLeaders": {"personId": 203507, "name": "Giannis Antetokounmpo", "jerseyNum": "34", "position": "F", "teamTricode": "MIL", "playerSlug": null, "points": 29, "rebounds": 21, "assists": 11}, "awayLeaders": {"personId": 203076, "name": "Anthony Davis", "jerseyNum": "3", "position": "F-C", "teamTricode": "LAL", "playerSlug": null, "points": 34, "rebounds": 23, "assists": 2}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}, {"gameId": "0022301046", "gameCode": "20240326/OKCNOP", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2024-03-27T00:00:00Z", "gameEt": "2024-03-26T20:00:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "gameLabel": "", "gameSubLabel": "", "seriesText": "", "seriesConference": "", "poRoundDesc": "", "gameSubtype": "", "homeTeam": {"teamId": 1610612740, "teamName": "Pelicans", "teamCity": "New Orleans", "teamTricode": "NOP", "wins": 44, "losses": 28, "score": 112, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 34}, {"period": 2, "periodType": "REGULAR", "score": 24}, {"period": 3, "periodType": "REGULAR", "score": 32}, {"period": 4, "periodType": "REGULAR", "score": 22}]}, "awayTeam": {"teamId": 1610612760, "teamName": "Thunder", "teamCity": "Oklahoma City", "teamTricode": "OKC", "wins": 50, "losses": 21, "score": 119, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 33}, {"period": 2, "periodType": "REGULAR", "score": 40}, {"period": 3, "periodType": "REGULAR", "score": 23}, {"period": 4, "periodType": "REGULAR", "score": 23}]}, "gameLeaders": {"homeLeaders": {"personId": 1629627, "name": "Zion Williamson", "jerseyNum": "1", "position": "F", "teamTricode": "NOP", "playerSlug": null, "points": 29, "rebounds": 5, "assists": 10}, "awayLeaders": {"personId": 1630581, "name": "Josh Giddey", "jerseyNum": "3", "position": "G", "teamTricode": "OKC", "playerSlug": null, "points": 25, "rebounds": 9, "assists": 4}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}, {"gameId": "0022301047", "gameCode": "20240326/DALSAC", "gameStatus": 3, "gameStatusText": "Final", "period": 4, "gameClock": "", "gameTimeUTC": "2024-03-27T02:00:00Z", "gameEt": "2024-03-26T22:00:00Z", "regulationPeriods": 4, "ifNecessary": false, "seriesGameNumber": "", "gameLabel": "", "gameSubLabel": "", "seriesText": "", "seriesConference": "", "poRoundDesc": "", "gameSubtype": "", "homeTeam": {"teamId": 1610612758, "teamName": "Kings", "teamCity": "Sacramento", "teamTricode": "SAC", "wins": 42, "losses": 30, "score": 96, "seed": null, "inBonus": null, "timeoutsRemaining": 0, "periods": [{"period": 1, "periodType": "REGULAR", "score": 28}, {"period": 2, "periodType": "REGULAR", "score": 25}, {"period": 3, "periodType": "REGULAR", "score": 23}, {"period": 4, "periodType": "REGULAR", "score": 20}]}, "awayTeam": {"teamId": 1610612742, "teamName": "Mavericks", "teamCity": "Dallas", "teamTricode": "DAL", "wins": 43, "losses": 29, "score": 132, "seed": null, "inBonus": null, "timeoutsRemaining": 1, "periods": [{"period": 1, "periodType": "REGULAR", "score": 31}, {"period": 2, "periodType": "REGULAR", "score": 27}, {"period": 3, "periodType": "REGULAR", "score": 38}, {"period": 4, "periodType": "REGULAR", "score": 36}]}, "gameLeaders": {"homeLeaders": {"personId": 1627734, "name": "Domantas Sabonis", "jerseyNum": "10", "position": "F-C", "teamTricode": "SAC", "playerSlug": null, "points": 12, "rebounds": 11, "assists": 9}, "awayLeaders": {"personId": 1629029, "name": "Luka Doncic", "jerseyNum": "77", "position": "F-G", "teamTricode": "DAL", "playerSlug": null, "points": 28, "rebounds": 11, "assists": 6}}, "pbOdds": {"team": null, "odds": 0.0, "suspended": 0}}]}}'

In [121]:
from nba_api.stats.endpoints import leaguedashlineups
leaguedashlineups.LeagueDashLineups().get_data_frames()[0]

,GROUP_SET,GROUP_ID,GROUP_NAME,TEAM_ID,TEAM_ABBREVIATION,GP,W,L,W_PCT,MIN,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,Lineups,-203484-203932-203999-1627750-1629008-,K. Caldwell-Pope - A. Gordon - N. Jokic - J. M...,1610612743,DEN,45,35,10,0.778,894.701667,...,1,1,14130,1,2,14128,14128,1,1,1
1,Lineups,-1628983-1629652-1630581-1631096-1631114-,S. Gilgeous-Alexander - L. Dort - J. Giddey - ...,1610612760,OKC,60,43,17,0.717,769.880000,...,3,2,14127,3,1,14129,14129,2,2,5
2,Lineups,-1627832-1628415-1630224-1630578-1631095-,F. VanVleet - D. Brooks - J. Green - A. Sengun...,1610612745,HOU,45,23,22,0.511,754.045000,...,2,4,14129,4,8,14130,14130,3,3,7631
3,Lineups,-203084-1627734-1628368-1628989-1631099-,H. Barnes - D. Sabonis - D. Fox - K. Huerter -...,1610612758,SAC,46,27,19,0.587,668.940000,...,4,3,14126,2,11,14126,14127,6,4,10
4,Lineups,-201144-203497-1626157-1630162-1630183-,M. Conley - R. Gobert - K. Towns - A. Edwards ...,1610612750,MIN,43,30,13,0.698,609.675000,...,6,7,14128,6,7,14126,14125,4,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Lineups,-203926-1626224-1628380-1630200-1630577-,D. McDermott - C. Osman - Z. Collins - T. Jone...,1610612759,SAS,3,0,3,0.000,10.783333,...,2116,2243,5801,1539,1890,1,12492,2770,2116,7631
1996,Lineups,-203995-1629652-1630598-1631096-1631114-,V. Micic - L. Dort - A. Wiggins - C. Holmgren ...,1610612760,OKC,3,2,1,0.667,10.783333,...,2410,1040,11308,2735,1890,9238,10217,2770,1656,2809
1997,Lineups,-204060-1628365-1629021-1630591-1631094-,J. Ingles - M. Fultz - M. Wagner - J. Suggs - ...,1610612753,ORL,5,4,1,0.800,10.770000,...,1371,1882,12229,1539,4738,9238,11401,2041,2020,1739
1998,Lineups,-1626156-1627752-1629020-1629637-1630559-,D. Russell - T. Prince - J. Vanderbilt - J. Ha...,1610612747,LAL,1,1,0,1.000,10.766667,...,1371,1352,1,673,4738,13753,1,2770,1864,2809
1999,Lineups,-202681-1626158-1627884-1629029-1629684-,K. Irving - R. Holmes - D. Jones Jr. - L. Donc...,1610612742,DAL,2,1,1,0.500,10.766667,...,1534,4842,1,2735,1890,9238,11401,2041,4257,12257

In [126]:
# Query nba.live.endpoints.scoreboard and  list games in localTimeZone
from datetime import datetime, timezone
from dateutil import parser
from nba_api.live.nba.endpoints import scoreboard

f = "{gameId}: {awayTeam} vs. {homeTeam} @ {gameTimeLTZ}" 

board = scoreboard.ScoreBoard()
print("ScoreBoardDate: " + board.score_board_date)
games = board.games.get_dict()
for game in games:
    gameTimeLTZ = parser.parse(game["gameTimeUTC"]).replace(tzinfo=timezone.utc).astimezone(tz=None)
    print(f.format(gameId=game['gameId'], awayTeam=game['awayTeam']['teamName'], homeTeam=game['homeTeam']['teamName'], gameTimeLTZ=gameTimeLTZ))

ScoreBoardDate: 2024-03-28
0022301060: Celtics vs. Hawks @ 2024-03-29 00:30:00+01:00
0022301061: Bucks vs. Pelicans @ 2024-03-29 01:00:00+01:00